apiVersion: apps/v1
kind: Deployment
metadata:
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - image: kowshhal/register
        imagePullPolicy: Always
        name: register
      restartPolicy: Always
---
  apiVersion: v1
  kind: Service
  spec:
    clusterIP: 10.152.183.174
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 30192
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: register
    type: NodePort
  