apiVersion: apps/v1
kind: Deployment
metadata:
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - image: kowshhal/search
        imagePullPolicy: Always
        name: search
      restartPolicy: Always
---
  apiVersion: v1
  kind: Service
  metadata:
  spec:
    clusterIP: 10.152.183.246
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 30048
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: search
    type: NodePort
  
