apiVersion: apps/v1
kind: Deployment
metadata:
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transfer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - image: kowshhal/transfer
        imagePullPolicy: Always
        name: transfer
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
spec:
  clusterIP: 10.152.183.175
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32355
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: transfer
  type: NodePort
