apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - image: kowshhal/transactions
        imagePullPolicy: Always
        name: transactions
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
spec:
  clusterIP: 10.152.183.182
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32595
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: transaction
  type: NodePort

